@startuml
left to right direction
actor "Usuario" as user

rectangle Calculadora {
    usecase "Sumar" as UC1
    usecase "Restar" as UC2
    usecase "Multiplicación" as UC3
    usecase "Dividir" as UC4

    user --> UC1
    user --> UC2
    user --> UC3
    user --> UC4
}
@enduml