@startuml
package es.dam.prog.ivanvm {

    class App {
        +main(args: String[])
    }

    package .calculadora {
        interface Calculable {
            +sumar(x: int, y: int): int
            +sumar(x: double, y: double): double
            +restar(x: double, y: double): double
            +multiplicar(x: double, y: double): double
            +dividir(x: double, y: double): double
        }

        class Calculadora implements Calculable {

        }
    }
}

App .. Calculable
@enduml